ecom-product-search:
  image:
    repository: saurabhgupta98989/ecom-product-search-service
    tag: 0.0.6-SNAPSHOT
  service:
    type: ClusterIP
    port: 80
ecom-product-service:
  image:
    repository: saurabhgupta98989/ecom-product-service
    tag: 0.0.4-SNAPSHOT
  service:
    type: ClusterIP
    port: 80
ecom-ui:
  image:
    repository: saurabhgupta98989/ecom-ui
    tag: 0.0.3
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  host: yourdomain.com
  certificateArn: arn:aws:acm:ap-south-1:xxxx:certificate/xxxx