ecom-product-search:
  image:
    repository: saurabhgupta98989/ecom-product-search-service
    tag: 0.0.5-SNAPSHOT
  service:
    type: LoadBalancer
    port: 80
ecom-product-service:
  image:
    repository: saurabhgupta98989/ecom-product-service
    tag: 0.0.3-SNAPSHOT
  service:
    type: LoadBalancer
    port: 80
ecom-ui:
  image:
    repository: saurabhgupta98989/ecom-ui
    tag: 0.0.2
  service:
    type: LoadBalancer
    port: 80
