apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ecom-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ecom-ui
  template:
    metadata:
      labels:
        app: ecom-ui
    spec:
      containers:
        - name: ecom-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 80