apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ecom-ui
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ecom-ui
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80